---

#
# graylog server handlers
#
# Restart only when changes are made.
#

- name: restart mongod
  service:
    name: mongod
    state: restarted
    enabled: yes

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: restart graylog-server
  service:
    name: graylog-server
    state: restarted
    enabled: yes

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
